name: ✨ Feature Request
description: This form is to request a new feature in nx-go.
labels: [ "type: enhancement" ]
body:
  - type: textarea
    id: solution
    attributes:
      label: Solution you'd like
      description: Please write a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: problem-related
    attributes:
      label: Is your feature request related to a problem?
      description: Please write a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      description: Please include a clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Is there any additional information or screenshots that you want to provide?
