name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e:
    name: End-to-end tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go_version: [ 1.22.0 ]
        node_version: [ 20.x ]
    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⚙ Setup
        uses: ./.github/actions/setup
        with:
          go_version: ${{ matrix.go_version }}
          node_version: ${{ matrix.node_version }}

      - name: 🎭 End-to-end tests
        run: pnpm nx affected --target=e2e --parallel

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⚙ Setup
        uses: ./.github/actions/setup
        with:
          go_version: 1.22.0
          node_version: 20.x

      - name: 🎈 Lint, test and build
        run: pnpm nx affected --target=lint,test,build --parallel=3

      - name: ⛳ SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
