name: Run PR checks

on: pull_request

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]
        go-version: [ 1.20.13, 1.21.6 ]
    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: Use Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 💼 Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: 🔧 Install dependencies
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.15.x
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: 🎈 Lint, test and build
        run: pnpm nx affected --target=lint,test,build --parallel --max-parallel=3

      - name: 🎭 End-to-end tests
        run: pnpm nx affected --target=e2e --parallel
