name: Release

on:
  workflow_dispatch:
    inputs:
      beta:
        description: 'Whether to publish a beta release'
        required: false
        default: false
        type: boolean
      dryRun:
        description: 'Whether to perform a dry run of the release process'
        required: false
        default: false
        type: boolean
      releaseAs:
        description: 'The version to release as (patch, minor, major)'
        required: false
        default: ''
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GH_RELEASE_TOKEN }}

      - name: ⚙ Setup
        uses: ./.github/actions/setup
        with:
          go_version: 1.25.6
          node_version: 22.x

      - name: Configure Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Check npm credentials
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 🏷 Version
        shell: bash
        run: pnpm nx run nx-go:version${{ inputs.beta && ':beta' || '' }} --dry-run=${{ inputs.dryRun }}${{ inputs.releaseAs && format(' --releaseAs={0}', inputs.releaseAs) || '' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
